"use client";

import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, TriangleAlert, ExternalLink } from "lucide-react";

/** Branded "Claude is working" loading block. */
export function ClaudeThinking({ label }: { label: string }) {
  return (
    <Card className="border-dashed">
      <CardContent className="py-14 flex flex-col items-center text-center gap-4">
        <div className="relative h-12 w-12">
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 2.2, repeat: Infinity, ease: "linear" }}
            className="absolute inset-0 rounded-full border-2 border-primary/25 border-t-primary"
          />
          <div className="absolute inset-0 flex items-center justify-center">
            <Sparkles className="h-4 w-4 text-primary" strokeWidth={1.5} />
          </div>
        </div>
        <div>
          <div className="font-display text-xl">{label}</div>
          <div className="text-sm text-muted-foreground mt-1">
            Running on your local Claude Code — this takes 20–60 seconds.
          </div>
        </div>
        <div className="flex gap-1.5 mt-1">
          {[0, 1, 2].map((i) => (
            <motion.span
              key={i}
              className="h-1.5 w-1.5 rounded-full bg-primary/60"
              animate={{ opacity: [0.3, 1, 0.3] }}
              transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.2 }}
            />
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

/** Shown when the Claude Code CLI isn't installed / logged in. */
export function ClaudeRequired({
  error,
  onRetry,
}: {
  error?: string;
  onRetry?: () => void;
}) {
  return (
    <Card className="border-[color:var(--chart-4)]/40 bg-[color:var(--chart-4)]/5">
      <CardContent className="py-12 px-6 text-center max-w-xl mx-auto">
        <div className="h-12 w-12 rounded-full bg-[color:var(--chart-4)]/15 mx-auto flex items-center justify-center mb-5">
          <TriangleAlert className="h-5 w-5 text-[color:var(--chart-4)]" strokeWidth={1.5} />
        </div>
        <div className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground mb-2">
          Claude Code needed
        </div>
        <h2 className="font-display text-2xl mb-3">This phase runs on Claude Code</h2>
        <p className="text-sm text-muted-foreground leading-relaxed mb-2">
          The analysis, ranking, website prompt, and outreach are generated by Claude Code running
          locally under your subscription — no API key. It isn&apos;t installed or logged in yet.
        </p>
        {error && (
          <p className="text-xs text-muted-foreground/80 italic mb-5 mt-2 break-words">{error}</p>
        )}
        <div className="flex items-center justify-center gap-2 mt-4 flex-wrap">
          <Button
            variant="outline"
            className="h-10 px-4"
            onClick={() => window.open("https://claude.com/claude-code", "_blank")}
          >
            <ExternalLink className="h-4 w-4 mr-2" strokeWidth={1.5} /> Install Claude Code
          </Button>
          {onRetry && (
            <Button className="h-10 px-4" onClick={onRetry}>
              Retry
            </Button>
          )}
        </div>
        <p className="text-[11px] text-muted-foreground/70 mt-5">
          After installing, run <code className="font-mono">claude</code> once in a terminal and sign in, then retry.
        </p>
      </CardContent>
    </Card>
  );
}
